export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MORE_MOVIES = "FETCH_MORE_MOVIES";
export const FETCH_MOVIES_LOADING = "FETCH_MOVIES_LOADING";
export const FETCH_MOVIES_ERROR = "FETCH_MOVIES_ERROR";
